name: "Dependency Vulnerability Scan"

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-8-tools-deps-slim-buster
      volumes:
        - "/home/runner/work/_actions":"/home/runner/work/_actions"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate pom.xml
        run: clojure -X:deps mvn-pom
      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
