name: "Dependency Vulnerability Scan"

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Install Clojure CLI
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.3.933.sh &&
          sudo bash ./linux-install-1.10.3.933.sh
      - name: Get M2 cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
      - name: Generate pom.xml
        run: clojure -X:deps mvn-pom
      - uses: snyk/actions/setup
      - name: Run Snyk to check for vulnerabilities
        run: snyk monitor --org=metabase --file=pom.xml 
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
