name: "Dependency Vulnerability Scan"

on: [push, pull_request]

jobs:
  analyze:
    runs-on: clojure:lein-alpine
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Generate pom.xml
      run: lein pom
    - uses: snyk/actions/setup@master
    - name: Run Snyk to check for vulnerabilities
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
